//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpnConnections.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VpnConnections.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color for connected.
        /// </summary>
        internal static string Accent_color_for_connected {
            get {
                return ResourceManager.GetString("Accent color for connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color for disconnected.
        /// </summary>
        internal static string Accent_color_for_disconnected {
            get {
                return ResourceManager.GetString("Accent color for disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string Behaviour {
            get {
                return ResourceManager.GetString("Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        internal static string Close_application {
            get {
                return ResourceManager.GetString("Close application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect only.
        /// </summary>
        internal static string Connect_only {
            get {
                return ResourceManager.GetString("Connect only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectingBackground {
            get {
                object obj = ResourceManager.GetObject("ConnectingBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectingForeground {
            get {
                object obj = ResourceManager.GetObject("ConnectingForeground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Connection_Name {
            get {
                return ResourceManager.GetString("Connection Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft\Network\Connections\Pbk\rasphone.pbk.
        /// </summary>
        internal static string DefaultPhonebook {
            get {
                return ResourceManager.GetString("DefaultPhonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect only.
        /// </summary>
        internal static string Disconnect_only {
            get {
                return ResourceManager.GetString("Disconnect only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging.
        /// </summary>
        internal static string Enable_logging {
            get {
                return ResourceManager.GetString("Enable logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connected.
        /// </summary>
        internal static string MessageConnected {
            get {
                return ResourceManager.GetString("MessageConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string MessageDefault {
            get {
                return ResourceManager.GetString("MessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnected.
        /// </summary>
        internal static string MessageDisconnected {
            get {
                return ResourceManager.GetString("MessageDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On connected only.
        /// </summary>
        internal static string On_connected_only {
            get {
                return ResourceManager.GetString("On connected only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On connection change.
        /// </summary>
        internal static string On_connection_change {
            get {
                return ResourceManager.GetString("On connection change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On disconnected only.
        /// </summary>
        internal static string On_disconnected_only {
            get {
                return ResourceManager.GetString("On disconnected only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only connected.
        /// </summary>
        internal static string Only_connected {
            get {
                return ResourceManager.GetString("Only connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only disconnected.
        /// </summary>
        internal static string Only_disconnected {
            get {
                return ResourceManager.GetString("Only disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration dialog.
        /// </summary>
        internal static string Open_configuration_dialog {
            get {
                return ResourceManager.GetString("Open configuration dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tool on startup.
        /// </summary>
        internal static string Run_tool_on_startup {
            get {
                return ResourceManager.GetString("Run tool on startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\Run.
        /// </summary>
        internal static string RunKey {
            get {
                return ResourceManager.GetString("RunKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings.json.
        /// </summary>
        internal static string SettingsFilename {
            get {
                return ResourceManager.GetString("SettingsFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification.
        /// </summary>
        internal static string Show_notification {
            get {
                return ResourceManager.GetString("Show notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon StatusActive {
            get {
                object obj = ResourceManager.GetObject("StatusActive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBackground {
            get {
                object obj = ResourceManager.GetObject("StatusBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusForeground {
            get {
                object obj = ResourceManager.GetObject("StatusForeground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle connection state.
        /// </summary>
        internal static string Toggle_connection_state {
            get {
                return ResourceManager.GetString("Toggle connection state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon connected color.
        /// </summary>
        internal static string Tray_icon_connected_color {
            get {
                return ResourceManager.GetString("Tray icon connected color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon disconnected color.
        /// </summary>
        internal static string Tray_icon_disconnected_color {
            get {
                return ResourceManager.GetString("Tray icon disconnected color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon left mouse button click.
        /// </summary>
        internal static string Tray_icon_left_mouse_button_click {
            get {
                return ResourceManager.GetString("Tray icon left mouse button click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon left mouse button double click.
        /// </summary>
        internal static string Tray_icon_left_mouse_button_double_click {
            get {
                return ResourceManager.GetString("Tray icon left mouse button double click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon right mouse button click.
        /// </summary>
        internal static string Tray_icon_right_mouse_button_click {
            get {
                return ResourceManager.GetString("Tray icon right mouse button click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon right mouse button double click.
        /// </summary>
        internal static string Tray_icon_right_mouse_button_double_click {
            get {
                return ResourceManager.GetString("Tray icon right mouse button double click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon visibility.
        /// </summary>
        internal static string Tray_icon_visibility {
            get {
                return ResourceManager.GetString("Tray icon visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
